### ISSUE TITLE
Import/Export not showing in the UI

### ISSUE THREAD

**Issue by rossmartin** [jsreport/jsreport-contrib-import-export#1]
I installed this extension and I see that it is loaded up when starting the jsreport server.js but the Import/Export buttons do not show up in the UI anywhere.  I think they are supposed to show up when looking at a template but they don't show?  Any ideas on why this is not working with the latest jsreport server version?

Thank you.

**Comment by pofider** [comment]
Thanks for the bug report.

The extension was not updated for the latest jsreport. I will fix it now...

**Comment by rossmartin** [comment]
Thanks for the quick reply and help!

**Comment by pofider** [comment]
Fixed in the latest 0.1.1 https://github.com/jsreport/jsreport-contrib-import-export/releases/tag/0.1.1
